# Generated by Django 4.0.3 on 2022-03-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
